ASP.NET_RazorPages/Entities/Category.cs
namespace ASP.NET_RazorPages.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string? Title { get; set; }
    }
}

ASP.NET_RazorPages/Entities/Product.cs
namespace ASP.NET_RazorPages.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public decimal Price { get; set; }
    }
}

ASP.NET_RazorPages/Models/CategoryListViewModel.cs
namespace ASP.NET_RazorPages.Models
{
    public class CategoryListViewModel
    {
        public IQueryable<CategoryViewModel>? Categories { get; set; }
    }
}

ASP.NET_RazorPages/Models/CategoryViewModel.cs
namespace ASP.NET_RazorPages.Models
{
    public class CategoryViewModel
    {
        public string? Title { get; set; }
    }
}

ASP.NET_RazorPages/Models/ErrorViewModel.cs
namespace ASP.NET_RazorPages.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET_RazorPages/Models/ProductCategoryListViewModel.cs
using ASP.NET_RazorPages.Entities;

namespace ASP.NET_RazorPages.Models
{
    public class ProductCategoryListViewModel
    {
        public IQueryable<ProductViewModel>? Products { get; set; }
        public IQueryable<CategoryViewModel>? Categories { get; set; }
    }
}

ASP.NET_RazorPages/Models/ProductViewModel.cs
namespace ASP.NET_RazorPages.Models
{
    public class ProductViewModel
    {
        public string? Name { get; set; }
        public decimal Price { get; set; }
    }
}

ASP.NET_RazorPages/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET_RazorPages.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ASP.NET_RazorPages/Areas/Candidate/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET_RazorPages.Areas.Candidate.Controllers
{
    [Area("Candidate")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ASP.NET_RazorPages/Controllers/HomeController.cs
using ASP.NET_RazorPages.Data;
using ASP.NET_RazorPages.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET_RazorPages.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProductDbContext _context;

        public HomeController(ProductDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var products = _context.Products
                .Select(p => new ProductViewModel { Name = p.Name, Price = p.Price });
            var categories = _context.Categories
                .Select(c => new CategoryViewModel { Title = c.Title });

            var vm = new ProductCategoryListViewModel
            {
                Categories = categories,
                Products = products
            };
            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ASP.NET_RazorPages/Pages/Product/Index.cshtml.cs
using ASP.NET_RazorPages.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASP.NET_RazorPages.Pages.Product
{
    public class IndexModel : PageModel
    {
        private readonly ProductDbContext _context;

        public IndexModel(ProductDbContext context)
        {
            _context = context;
        }

        public List<Entities.Product> Products { get; set; } = new List<Entities.Product>();

        public string Info { get; set; }

        [BindProperty]
        public Entities.Product Product { get; set; }

        public void OnGet(string info = "")
        {
            Products = _context.Products.ToList();
            Info = info;
        }

        public IActionResult OnPost()
        {
            if (Product.Id == 0)
            {
                _context.Products.Add(Product);
                Info = $"{Product.Name} added successfully";
            }
            else
            {
                var existingProduct = _context.Products.Find(Product.Id);
                if (existingProduct != null)
                {
                    existingProduct.Name = Product.Name;
                    existingProduct.Price = Product.Price;
                    Info = $"{Product.Name} updated successfully";
                }
                else
                {
                    Info = "Product not found";
                }
            }

            _context.SaveChanges();
            return RedirectToPage("Index", new { info = Info });
        }

        public IActionResult OnGetEdit(int id)
        {
            Product = _context.Products.Find(id);

            if (Product == null)
            {
                Info = "Product not found";
                return RedirectToPage("Index", new { info = Info });
            }

            return Page();
        }

        public IActionResult OnGetDelete(int id)
        {
            var product = _context.Products.Find(id);
            if (product != null)
            {
                _context.Products.Remove(product);
                _context.SaveChanges();
                Info = $"{product.Name} deleted successfully";
            }
            else
            {
                Info = "Product not found";
            }

            return RedirectToPage("Index", new { info = Info });
        }
    }
}

ASP.NET_RazorPages/ViewComponents/CategoryListViewComponent.cs
using ASP.NET_RazorPages.Data;
using ASP.NET_RazorPages.Entities;
using ASP.NET_RazorPages.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace ASP.NET_RazorPages.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ProductDbContext _context;

        public CategoryListViewComponent(ProductDbContext context)
        {
            _context = context;
        }

        public ViewViewComponentResult Invoke()
        {
            var categories = _context.Categories
                .Select(c => new CategoryViewModel { Title = c.Title });
            return View(
                new CategoryListViewModel
                {
                    Categories = categories
                });
        }
    }
}

ASP.NET_RazorPages/Areas/Admin/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section>
    <h2>Hello Admin Module User</h2>
    <hr style="background-color:springgreen"/>
</section>

ASP.NET_RazorPages/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson4App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson4App.styles.css" asp-append-version="true" />
</head>
<body>
    <h1>Admin Module</h1>
    <div class="container">
            
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lesson4App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET_RazorPages/Areas/Candidate/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/Candidate/Views/Shared/_CandidateLayout.cshtml";
}

<section>
    <h2>Hello Candidate Module User</h2>
    <hr style="background-color:springgreen"/>
</section>

ASP.NET_RazorPages/Areas/Candidate/Views/Shared/_CandidateLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson4App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson4App.styles.css" asp-append-version="true" />
</head>
<body>
    <h1>Candidate Module</h1>
    <div class="container">
            
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lesson4App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET_RazorPages/Pages/Product/Index.cshtml
@page
@model ASP.NET_RazorPages.Pages.Product.IndexModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@if (!string.IsNullOrEmpty(Model.Info))
{
    <div class="alert alert-success" role="alert">
        @Model.Info
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">#</th>
            <th scope="col">#</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price$</td>
                <td>
                    <a asp-page-handler="Edit" asp-route-id="@item.Id" class="btn btn-outline-warning">Edit</a>
                </td>
                <td>
                    <a asp-page-handler="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<form class="col-5" method="post">
    <div class="mb-3">
        <label class="form-label">Product Name</label>
        <input asp-for="Product.Name" class="form-control" />
    </div>
    <div class="mb-3">
        <label class="form-label">Product Price</label>
        <input asp-for="Product.Price" class="form-control" />
    </div>
    <button type="submit" class="btn btn-success">
        @(Model.Product == null || Model.Product.Id == 0 ? "Add New Product" : "Edit Product")
    </button>
</form>

ASP.NET_RazorPages/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASP.NET_RazorPages/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_RazorPages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NET_RazorPages.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET_RazorPages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP.NET_RazorPages - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>